require("oriol.remap")
require("oriol.set")
require("oriol.lazy")
require("oriol.colors")
require("oriol.autocmd")
require("oriol.plugin.telescope")
require("oriol.plugin.treesitter")
require("oriol.plugin.lualine")
require("oriol.plugin.undotree")
require("oriol.plugin.indentline")
require("oriol.plugin.lsp")
require("oriol.plugin.cmp")
require("oriol.plugin.colorizer")
require("oriol.plugin.nvimtree")
require("oriol.plugin.pairs")
require("oriol.plugin.comment")
require("oriol.plugin.null-ls") -- needs to init after lsp-zero setup
