
[cursor]
blink_interval = 500

[cursor.style]
blinking = "Off"

[env]
TERM = "xterm-256color"

[font]
size = 14.5

[font.normal]
family = "SF Mono"
# family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.7

[general]
import = ["/home/oriol/.config/alacritty/colorschemes/digerati.toml"]
