#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME ls-tree --name-only --full-name main | sort | fzf)
    selected=$(find ~/Projects -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux source ~/.config/tmux/tmux.conf \; new-session -s $selected_name -c $selected > /dev/null 2>&1
    exit 0
fi

if  tmux has-session -t=$selected_name 2> /dev/null; then
 current_session=$(tmux display-message -p '#S')
    if [[ "$current_session" == "$selected_name" ]]; then
        tmux switch-client -t "$selected_name"
        tmux send-keys "cd \"$selected\"" Enter
        exit 0
    fi
    # tmux source ~/.config/tmux/tmux.conf \; new-session -ds $selected_name -c $selected > /dev/null 2>&1
fi

if  tmux has-session -t=$selected_name 2> /dev/null; then
    tmux a -t $selected_name > /dev/null 2>&1
fi

tmux switch-client -t $selected_name
